// Code generated by Remote Build Service. DO NOT EDIT.
// Build ID: {{.BuildID}}
// Generated at: {{.GeneratedAt}}

package main

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/health"
	"google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/reflection"
{{if .EnableMetrics}}
	"github.com/prometheus/client_golang/prometheus/promhttp"
{{end}}
{{if .EnableTracing}}
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
{{end}}
{{if .EnableGateway}}
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
{{end}}

	// Interceptor imports
{{range .InterceptorImports}}
	{{.Alias}} "{{.Path}}"
{{end}}

	// Service implementation imports
{{range .ServiceImports}}
	{{.Alias}} "{{.Path}}"
{{end}}

	// Generated proto imports
{{range .ProtoImports}}
	{{.Alias}} "{{.Path}}"
{{end}}
)

// Config holds the server configuration
type Config struct {
	GRPCAddress    string
	HTTPAddress    string
	ShutdownTimeout time.Duration
	TLSCertFile    string
	TLSKeyFile     string
}

func main() {
	// Initialize logger
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	// Load configuration
	cfg := loadConfig()

	// Run the server
	if err := run(context.Background(), cfg, logger); err != nil {
		logger.Error("server error", "error", err)
		os.Exit(1)
	}
}

func loadConfig() Config {
	return Config{
		GRPCAddress:     getEnv("GRPC_ADDRESS", "{{.GRPCAddress}}"),
		HTTPAddress:     getEnv("HTTP_ADDRESS", "{{.HTTPAddress}}"),
		ShutdownTimeout: getDurationEnv("SHUTDOWN_TIMEOUT", {{.ShutdownTimeout}}*time.Second),
		TLSCertFile:     getEnv("TLS_CERT_FILE", "{{.TLSCertFile}}"),
		TLSKeyFile:      getEnv("TLS_KEY_FILE", "{{.TLSKeyFile}}"),
	}
}

func run(ctx context.Context, cfg Config, logger *slog.Logger) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	// Build gRPC server options
	opts := []grpc.ServerOption{}

	// Add TLS if configured
{{if .TLSEnabled}}
	creds, err := credentials.NewServerTLSFromFile(cfg.TLSCertFile, cfg.TLSKeyFile)
	if err != nil {
		return fmt.Errorf("failed to load TLS credentials: %w", err)
	}
	opts = append(opts, grpc.Creds(creds))
{{end}}

	// Add interceptors
	unaryInterceptors := []grpc.UnaryServerInterceptor{
{{range .UnaryInterceptors}}
		{{.}},
{{end}}
	}
	
	streamInterceptors := []grpc.StreamServerInterceptor{
{{range .StreamInterceptors}}
		{{.}},
{{end}}
	}

	opts = append(opts, grpc.ChainUnaryInterceptor(unaryInterceptors...))
	opts = append(opts, grpc.ChainStreamInterceptor(streamInterceptors...))

	// Create gRPC server
	grpcServer := grpc.NewServer(opts...)

	// Initialize dependencies
	deps := initDependencies(ctx, cfg, logger)

	// Register services
{{range .Services}}
	{{.Registration}}
{{end}}

{{if .EnableHealthCheck}}
	// Register health check service
	healthServer := health.NewServer()
	grpc_health_v1.RegisterHealthServer(grpcServer, healthServer)
{{range .Services}}
	healthServer.SetServingStatus("{{.ProtoServiceName}}", grpc_health_v1.HealthCheckResponse_SERVING)
{{end}}
{{end}}

{{if .EnableReflection}}
	// Enable reflection
	reflection.Register(grpcServer)
{{end}}

	// Start gRPC server
	grpcListener, err := net.Listen("tcp", cfg.GRPCAddress)
	if err != nil {
		return fmt.Errorf("failed to listen on %s: %w", cfg.GRPCAddress, err)
	}

	errChan := make(chan error, 1)

	go func() {
		logger.Info("starting gRPC server", "address", cfg.GRPCAddress)
		if err := grpcServer.Serve(grpcListener); err != nil {
			errChan <- fmt.Errorf("gRPC server error: %w", err)
		}
	}()

{{if .EnableGateway}}
	// Start HTTP gateway
	go func() {
		if err := runHTTPGateway(ctx, cfg, logger); err != nil {
			errChan <- fmt.Errorf("HTTP gateway error: %w", err)
		}
	}()
{{end}}

{{if .EnableMetrics}}
	// Start metrics server
	go func() {
		metricsAddr := getEnv("METRICS_ADDRESS", ":9090")
		logger.Info("starting metrics server", "address", metricsAddr)
		http.Handle("/metrics", promhttp.Handler())
		if err := http.ListenAndServe(metricsAddr, nil); err != nil {
			logger.Error("metrics server error", "error", err)
		}
	}()
{{end}}

	// Wait for shutdown signal
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	select {
	case sig := <-sigChan:
		logger.Info("received shutdown signal", "signal", sig)
	case err := <-errChan:
		return err
	case <-ctx.Done():
		logger.Info("context cancelled")
	}

	// Graceful shutdown
	logger.Info("shutting down gracefully", "timeout", cfg.ShutdownTimeout)
	
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), cfg.ShutdownTimeout)
	defer shutdownCancel()

{{if .EnableHealthCheck}}
	// Set health status to not serving
{{range .Services}}
	healthServer.SetServingStatus("{{.ProtoServiceName}}", grpc_health_v1.HealthCheckResponse_NOT_SERVING)
{{end}}
{{end}}

	// Stop gRPC server
	stopped := make(chan struct{})
	go func() {
		grpcServer.GracefulStop()
		close(stopped)
	}()

	select {
	case <-shutdownCtx.Done():
		logger.Warn("graceful shutdown timed out, forcing stop")
		grpcServer.Stop()
	case <-stopped:
		logger.Info("server stopped gracefully")
	}

	// Cleanup dependencies
	if err := deps.Close(); err != nil {
		logger.Error("error closing dependencies", "error", err)
	}

	return nil
}

{{if .EnableGateway}}
func runHTTPGateway(ctx context.Context, cfg Config, logger *slog.Logger) error {
	mux := runtime.NewServeMux()
	opts := []grpc.DialOption{grpc.WithInsecure()}

{{range .GatewayRegistrations}}
	if err := {{.}}; err != nil {
		return fmt.Errorf("failed to register gateway: %w", err)
	}
{{end}}

	logger.Info("starting HTTP gateway", "address", cfg.HTTPAddress)
	return http.ListenAndServe(cfg.HTTPAddress, mux)
}
{{end}}

// Dependencies holds shared dependencies for services
type Dependencies struct {
	Logger *slog.Logger
	// Add more shared dependencies here
}

func initDependencies(ctx context.Context, cfg Config, logger *slog.Logger) *Dependencies {
	return &Dependencies{
		Logger: logger,
	}
}

func (d *Dependencies) Close() error {
	// Cleanup logic here
	return nil
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func getDurationEnv(key string, defaultValue time.Duration) time.Duration {
	if value := os.Getenv(key); value != "" {
		if d, err := time.ParseDuration(value); err == nil {
			return d
		}
	}
	return defaultValue
}
